export const SPACE_WORKSTATIONS = Object.freeze([
  {
    id: "trend-prophet",
    name: "Trend Prophet",
    role: "趋势预言师",
    summary: "负责扫描社区热度、情绪波动与支持率，第一时间给出趋势判断。",
    board: "公告牌：今日主看板是「支持率异动预警」。",
    status: "桌面状态：三块图表同时刷新，蓝色波峰正在上扬。",
    activity: "Debugging code...",
    hoverActivity: "Trend spike!",
    dialogue: {
      line: "我刚捕捉到一段支持率异动，蓝色波峰还在上扬。",
      status: "热度扫描中 · 下一轮预警准备就绪",
    },
    accent: "#7ba4db",
    deskColor: "#1f2a37",
    outfitColor: "#86a8e7",
    position: { x: -10.5, y: 0, z: -4.5 },
    focus: { x: -10.5, y: 2.7, z: -4.2 },
    cameraOffset: { x: 4.8, y: 3.7, z: 7.4 },
    facing: Math.PI / 8,
    decor: "charts",
    avatar: {
      type: "human",
      view: "left",
      skin: "#ffd8bd",
      hair: "#f0cc8b",
      hairShade: "#b88a6b",
      shirt: "#86a8e7",
      shadow: "#28324d",
      accessory: "monitor",
      label: "Ari",
    },
  },
  {
    id: "signal-smith",
    name: "Signal Smith",
    role: "信号锻造师",
    summary: "把实时事件、标签和工单拼成可执行信号，驱动整个空间的响应。",
    board: "公告牌：正在整理「新话题流量分层」。",
    status: "桌面状态：双显示器展开信号矩阵，右侧台灯常亮。",
    activity: "Reading paper...",
    hoverActivity: "Signal locked.",
    dialogue: {
      line: "事件、标签和工单已经合成一条可执行信号。",
      status: "信号矩阵在线 · 等待分发",
    },
    accent: "#c9a0dc",
    deskColor: "#261f31",
    outfitColor: "#74b7d8",
    position: { x: -5.2, y: 0, z: -1.4 },
    focus: { x: -5.2, y: 2.7, z: -1.5 },
    cameraOffset: { x: 4.7, y: 3.6, z: 7.2 },
    facing: Math.PI / 14,
    decor: "antenna",
    avatar: {
      type: "human",
      view: "front",
      skin: "#ffd0b9",
      hair: "#a96b55",
      hairShade: "#704154",
      shirt: "#62a6c7",
      shadow: "#30233b",
      accessory: "paper",
      label: "Bea",
    },
  },
  {
    id: "prompt-director",
    name: "Prompt Director",
    role: "提示词导演",
    summary: "统一角色语气、任务上下文与工作节奏，协调 5 个角色之间的协作风格。",
    board: "公告牌：本轮重点是「人物设定统一与信息表达」。",
    status: "桌面状态：中央屏幕显示任务分镜，便签贴满边框。",
    activity: "Writing report...",
    hoverActivity: "Scene notes ready.",
    dialogue: {
      line: "角色语气已统一，下一步可以把任务节奏压得更清楚。",
      status: "提示词分镜中 · 协作风格校准",
    },
    accent: "#ff9f43",
    deskColor: "#35271d",
    outfitColor: "#6f9d9a",
    position: { x: 0.2, y: 0, z: 1.2 },
    focus: { x: 0.2, y: 2.75, z: 1.1 },
    cameraOffset: { x: 0, y: 3.8, z: 8.2 },
    facing: 0,
    decor: "notes",
    avatar: {
      type: "human",
      view: "front",
      skin: "#ffe0c5",
      hair: "#ff793f",
      hairShade: "#a94833",
      shirt: "#6f9d9a",
      shadow: "#3c425d",
      accessory: "notes",
      label: "Carol",
    },
  },
  {
    id: "motion-keeper",
    name: "Motion Keeper",
    role: "动效守护者",
    summary: "负责空间中的镜头、旋转与交互动效，让整个房间保持沉浸感。",
    board: "公告牌：正在校准「镜头聚焦与过渡节奏」。",
    status: "桌面状态：桌下环形光带开启，屏幕显示相机曲线。",
    activity: "Testing motion...",
    hoverActivity: "Motion synced.",
    dialogue: {
      line: "镜头曲线已经收稳，轻点角色时会保留空间连续感。",
      status: "动效校准中 · 环形光带稳定",
    },
    accent: "#7ecf8e",
    deskColor: "#1d2e24",
    outfitColor: "#e56f48",
    position: { x: 5.6, y: 0, z: -1.5 },
    focus: { x: 5.6, y: 2.7, z: -1.4 },
    cameraOffset: { x: -4.7, y: 3.6, z: 7.2 },
    facing: -Math.PI / 14,
    decor: "ringlight",
    avatar: {
      type: "human",
      view: "right",
      skin: "#6b3c2f",
      hair: "#2b2e43",
      hairShade: "#151929",
      shirt: "#e56f48",
      shadow: "#232b43",
      accessory: "glasses",
      label: "Mika",
    },
  },
  {
    id: "qa-sentinel",
    name: "QA Sentinel",
    role: "验收哨兵",
    summary: "专注验收与巡检，确保工位信息、公告牌与交互状态始终正确。",
    board: "公告牌：待确认「场景复位、重复进入、故障提示」。",
    status: "桌面状态：工位旁的检查灯是绿色，测试清单保持展开。",
    activity: "Analyzing log...",
    hoverActivity: "Checks green.",
    dialogue: {
      line: "我会盯住场景复位、重复进入和弹窗关闭这几条验收线。",
      status: "巡检清单展开 · 暂无异常",
    },
    accent: "#ff6b6b",
    deskColor: "#341f23",
    outfitColor: "#59627b",
    position: { x: 10.7, y: 0, z: -4.4 },
    focus: { x: 10.7, y: 2.75, z: -4.1 },
    cameraOffset: { x: -4.8, y: 3.7, z: 7.4 },
    facing: -Math.PI / 8,
    decor: "checklist",
    avatar: {
      type: "robot",
      view: "front",
      skin: "#f8fbff",
      hair: "#f8fbff",
      hairShade: "#9aa7c2",
      shirt: "#59627b",
      shadow: "#222a42",
      accessory: "robot-arms",
      label: "Dave",
    },
  },
]);

export const DEFAULT_WORKSTATION_ID = SPACE_WORKSTATIONS[0].id;
